name: PR Validation
on:
  pull_request: {}
jobs:
  main:
    name: Build and Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          VALIDATE_WEBIDL: false